### ISSUE TITLE
reduction.py fails to get filenames

### ISSUE THREAD

**Issue by aswheaton** [aswheaton/fits-reducer#2]
Python exits with error:

```
Traceback (most recent call last):
  File "reduction.py", line 278, in <module>
    main()
  File "reduction.py", line 207, in main
    raw_dark_list, raw_flat_list, raw_target_list, raw_std_star_list = get_lists(data_folder)
  File "reduction.py", line 83, in get_lists
    _, _, filenames = next(walk(dir), (None, None, []))
  File "/usr/lib64/python2.7/os.py", line 276, in walk
    names = listdir(top)
```

**Comment by SlothInABox** [comment]
Ensure that you are running python3 rather than python. Python3 does not give me this error. Running python also seems to struggle with astropy.
